name: test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          # - "macos-latest"
          - "windows-latest"
        perl:
          - "5.32"
          - "5.30"
          - "5.28"
          - "5.26"
          - "5.24"
          - "5.22"
          - "5.20"
          - "5.18"
          - "5.16"
          - "5.14"
          - "5.12"
          - "5.10"
          - "5.8"
          - "5.6"
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - name: install Exporter
        run: |
          curl -LO https://cpan.metacpan.org/authors/id/T/TO/TODDR/Exporter-5.74.tar.gz
          tar xzvf Exporter-5.74.tar.gz
          cd Exporter-5.74
          perl Makefile.PL
          make
          make install
      - name: install File::Path
        run: |
          curl -LO http://www.cpan.org/authors/id/J/JK/JKEENAN/File-Path-2.18.tar.gz
          tar xzvf File-Path-2.18.tar.gz
          cd File-Path-2.18
          perl Makefile.PL
          make
          make install
      - run: prove -lv t
